### ISSUE TITLE
Unable to migrate containers

### ISSUE THREAD

**Issue by returntrip** [debarshiray/toolbox#283]
I am getting this error when entering a toolbox for the first time after having rebooted my Silverblue 31 PC.

`toolbox: unable to migrate containers: Podman version couldn't be read`

The second time i try to enter there is no error and can enter the toolbox without issues.

Versions in use:
toolbox-0.0.14-1.fc31.noarch
crun-0.10-1.fc31.x86_64
podman-1.6.0-4.fc31.x86_64

Verbose output:

```
[returntrip@rauros ~]$ toolbox -v enter
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user returntrip
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55aecc2f03d3]

goroutine 1 [running]:
panic(0x55aeccc3c380, 0x55aecdda0140)
	/usr/lib/golang/src/runtime/panic.go:722 +0x2c6 fp=0xc000546088 sp=0xc000545ff8 pc=0x55aecb3a2136
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:199
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:394 +0x3f0 fp=0xc0005460b8 sp=0xc000546088 pc=0x55aecb3b7e70
github.com/containers/libpod/libpod.(*Runtime).getPodNetwork(0xc000412000, 0xc00044c8c0, 0x40, 0xc000570620, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/networking_linux.go:31 +0x63 fp=0xc0005461b8 sp=0xc0005460b8 pc=0x55aecc2f03d3
github.com/containers/libpod/libpod.(*Container).refreshCNI(0xc00049cf50, 0x0, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/container_internal_linux.go:1332 +0xe4 fp=0xc000546308 sp=0xc0005461b8 pc=0x55aecc2d6d34
github.com/containers/libpod/libpod.(*Container).refresh(0xc00049cf50, 0x55aecde5cf38, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/container_internal.go:625 +0x3a4 fp=0xc000546440 sp=0xc000546308 pc=0x55aecc2bd7f4
github.com/containers/libpod/libpod.(*Runtime).refresh(0xc000412000, 0xc000483820, 0x1f, 0x0, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/runtime.go:1344 +0x17d fp=0xc000546598 sp=0xc000546440 pc=0x55aecc3144bd
github.com/containers/libpod/libpod.makeRuntime(0x55aeccee9fa0, 0xc0000400f0, 0xc000412000, 0x0, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/runtime.go:1225 +0x14d4 fp=0xc000546c68 sp=0xc000546598 pc=0x55aecc311694
github.com/containers/libpod/libpod.newRuntimeFromConfig(0x55aeccee9fa0, 0xc0000400f0, 0x0, 0x0, 0xc000547778, 0x0, 0x0, 0xc000412000, 0x0, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/runtime.go:729 +0x708 fp=0xc0005476f8 sp=0xc000546c68 pc=0x55aecc30dea8
github.com/containers/libpod/libpod.NewRuntime(...)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/libpod/runtime.go:427
github.com/containers/libpod/cmd/podman/libpodruntime.getRuntime(0x55aeccee9fa0, 0xc0000400f0, 0xc000547b10, 0x55ae01000000, 0xc00008ca80, 0x7fbf220e4460, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/cmd/podman/libpodruntime/runtime.go:180 +0xc8d fp=0xc000547940 sp=0xc0005476f8 pc=0x55aecc3d973d
github.com/containers/libpod/cmd/podman/libpodruntime.GetRuntime(...)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/cmd/podman/libpodruntime/runtime.go:33
main.setupRootless(0x55aecddc0340, 0xc0003185c0, 0x0, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/cmd/podman/main_local.go:165 +0x14b fp=0xc000547cd0 sp=0xc000547940 pc=0x55aecc4bf7bb
main.before(0x55aecddc0340, 0xc0003185c0, 0x0, 0x2, 0x1, 0xc0000108e0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/cmd/podman/main.go:124 +0xd2 fp=0xc000547d28 sp=0xc000547cd0 pc=0x55aecc4be0c2
main.glob..func68(0x55aecddc0340, 0xc0003185c0, 0x0, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/cmd/podman/main.go:78 +0x4b fp=0xc000547d68 sp=0xc000547d28 pc=0x55aecc4fa16b
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x55aecddc0340, 0xc00003c0e0, 0x2, 0x2, 0x55aecddc0340, 0xc00003c0e0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:805 +0x56d fp=0xc000547e40 sp=0xc000547d68 pc=0x55aecb56d95d
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x55aecddc05c0, 0x6, 0xc0000400a7, 0x8)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:914 +0x2fd fp=0xc000547f18 sp=0xc000547e40 pc=0x55aecb56e2ad
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/cmd/podman/main.go:160 +0xb2 fp=0xc000547f60 sp=0xc000547f18 pc=0x55aecc4be312
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x226 fp=0xc000547fe0 sp=0xc000547f60 pc=0x55aecb3a3ea6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000547fe8 sp=0xc000547fe0 pc=0x55aecb3d0a81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x55aecce8a3a8, 0x55aecde2f680, 0x1411, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000088fb0 sp=0xc000088f90 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:253 +0xbb fp=0xc000088fe0 sp=0xc000088fb0 pc=0x55aecb3a413b
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000088fe8 sp=0xc000088fe0 pc=0x55aecb3d0a81
created by runtime.init.6
	/usr/lib/golang/src/runtime/proc.go:242 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x55aecce8a3a8, 0x55aecde319a0, 0x140c, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0000897a8 sp=0xc000089788 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.bgsweep(0xc0000b0000)
	/usr/lib/golang/src/runtime/mgcsweep.go:89 +0x135 fp=0xc0000897d8 sp=0xc0000897a8 pc=0x55aecb396615
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000897e0 sp=0xc0000897d8 pc=0x55aecb3d0a81
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:210 +0x5e

goroutine 4 [sleep]:
runtime.gopark(0x55aecce8a3a8, 0x55aecde31f80, 0x55aecb3a1313, 0x2)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000089f00 sp=0xc000089ee0 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.scavengeSleep(0xc000000001, 0xc35000, 0x1401)
	/usr/lib/golang/src/runtime/mgcscavenge.go:232 +0xc4 fp=0xc000089f38 sp=0xc000089f00 pc=0x55aecb395aa4
runtime.bgscavenge(0xc0000b0000)
	/usr/lib/golang/src/runtime/mgcscavenge.go:346 +0x332 fp=0xc000089fd8 sp=0xc000089f38 pc=0x55aecb395e12
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000089fe0 sp=0xc000089fd8 pc=0x55aecb3d0a81
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:211 +0x80

goroutine 5 [finalizer wait]:
runtime.gopark(0x55aecce8a3a8, 0x55aecde5ce90, 0x1410, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000088758 sp=0xc000088738 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:175 +0xa7 fp=0xc0000887e0 sp=0xc000088758 pc=0x55aecb38c4a7
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000887e8 sp=0xc0000887e0 pc=0x55aecb3d0a81
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:156 +0x63

goroutine 6 [syscall]:
runtime.notetsleepg(0x55aecde44300, 0x1296d0f80, 0x0)
	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc00008a760 sp=0xc00008a730 pc=0x55aecb37eb08
runtime.timerproc(0x55aecde442e0)
	/usr/lib/golang/src/runtime/time.go:311 +0x2f5 fp=0xc00008a7d8 sp=0xc00008a760 pc=0x55aecb3c1615
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00008a7e0 sp=0xc00008a7d8 pc=0x55aecb3d0a81
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110

goroutine 40 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0004716c0, 0x55aecb371418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00008af60 sp=0xc00008af40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00006ca00)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc00008afd8 sp=0xc00008af60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00008afe0 sp=0xc00008afd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0002f3ed0, 0x55aecb371418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00008b760 sp=0xc00008b740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00005c500)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc00008b7d8 sp=0xc00008b760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00008b7e0 sp=0xc00008b7d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0002f3ef0, 0x55aecb371418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000084760 sp=0xc000084740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000060f00)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0000847d8 sp=0xc000084760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000847e0 sp=0xc0000847d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 51 [syscall]:
runtime.notetsleepg(0x55aecde5d680, 0xffffffffffffffff, 0xc000084fc8)
	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000084f98 sp=0xc000084f68 pc=0x55aecb37eb08
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e fp=0xc000084fc0 sp=0xc000084f98 pc=0x55aecb3b8c8e
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24 fp=0xc000084fe0 sp=0xc000084fc0 pc=0x55aecb991da4
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x55aecb3d0a81
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43

goroutine 52 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0002f3ec0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a4760 sp=0xc0004a4740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00005a000)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a47d8 sp=0xc0004a4760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a47e0 sp=0xc0004a47d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 53 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0002f3ee0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a4f60 sp=0xc0004a4f40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00005ea00)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a4fd8 sp=0xc0004a4f60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a4fe0 sp=0xc0004a4fd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 54 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0002f3f00, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a5760 sp=0xc0004a5740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000063400)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a57d8 sp=0xc0004a5760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a57e0 sp=0xc0004a57d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc000320750, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00008bf60 sp=0xc00008bf40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000065900)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc00008bfd8 sp=0xc00008bf60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00008bfe0 sp=0xc00008bfd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0004716b0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a0760 sp=0xc0004a0740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000068000)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a07d8 sp=0xc0004a0760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a07e0 sp=0xc0004a07d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 14 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc000320760, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a0f60 sp=0xc0004a0f40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00006a500)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a0fd8 sp=0xc0004a0f60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a0fe0 sp=0xc0004a0fd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 15 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0004716d0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a1760 sp=0xc0004a1740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00006ef00)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a17d8 sp=0xc0004a1760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a17e0 sp=0xc0004a17d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 55 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc000320770, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a5f60 sp=0xc0004a5f40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000071400)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a5fd8 sp=0xc0004a5f60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a5fe0 sp=0xc0004a5fd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 16 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc000320780, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a1f60 sp=0xc0004a1f40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000073900)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a1fd8 sp=0xc0004a1f60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a1fe0 sp=0xc0004a1fd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 56 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc000320790, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a6760 sp=0xc0004a6740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000076000)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a67d8 sp=0xc0004a6760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a67e0 sp=0xc0004a67d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 66 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0003207a0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a2760 sp=0xc0004a2740 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc000078500)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a27d8 sp=0xc0004a2760 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a27e0 sp=0xc0004a27d8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 57 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0003207b0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a6f60 sp=0xc0004a6f40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00007aa00)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a6fd8 sp=0xc0004a6f60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a6fe0 sp=0xc0004a6fd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 67 [GC worker (idle)]:
runtime.gopark(0x55aecce8a240, 0xc0003207c0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0004a2f60 sp=0xc0004a2f40 pc=0x55aecb3a4296
runtime.gcBgMarkWorker(0xc00007cf00)
	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc0004a2fd8 sp=0xc0004a2f60 pc=0x55aecb38fed5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004a2fe0 sp=0xc0004a2fd8 pc=0x55aecb3d0a81
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79

goroutine 41 [chan receive]:
runtime.gopark(0x55aecce8a3a8, 0xc00041d6d8, 0x7fbf220e170e, 0x3)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0000866d0 sp=0xc0000866b0 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.chanrecv(0xc00041d680, 0xc0000867b0, 0xc0003f3401, 0xc00041d680)
	/usr/lib/golang/src/runtime/chan.go:524 +0x2ec fp=0xc000086760 sp=0xc0000866d0 pc=0x55aecb37949c
runtime.chanrecv2(0xc00041d680, 0xc0000867b0, 0x55aecba3412b)
	/usr/lib/golang/src/runtime/chan.go:411 +0x2b fp=0xc000086790 sp=0xc000086760 pc=0x55aecb37919b
github.com/containers/libpod/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x55aecde32ec0)
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:990 +0x8d fp=0xc0000867d8 sp=0xc000086790 pc=0x55aecbb321ad
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000867e0 sp=0xc0000867d8 pc=0x55aecb3d0a81
created by github.com/containers/libpod/vendor/k8s.io/klog.init.0
	/builddir/build/BUILD/libpod-b02b072832cac26d7cc468d713303843d2935a36/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:404 +0x6e

goroutine 22 [timer goroutine (idle)]:
runtime.gopark(0x55aecce8a3a8, 0x55aecde44360, 0x1415, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000085f60 sp=0xc000085f40 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.timerproc(0x55aecde44360)
	/usr/lib/golang/src/runtime/time.go:303 +0x27f fp=0xc000085fd8 sp=0xc000085f60 pc=0x55aecb3c159f
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000085fe0 sp=0xc000085fd8 pc=0x55aecb3d0a81
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110

goroutine 58 [timer goroutine (idle)]:
runtime.gopark(0x55aecce8a3a8, 0x55aecde44460, 0x1415, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000016f60 sp=0xc000016f40 pc=0x55aecb3a4296
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.timerproc(0x55aecde44460)
	/usr/lib/golang/src/runtime/time.go:303 +0x27f fp=0xc000016fd8 sp=0xc000016f60 pc=0x55aecb3c159f
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000016fe0 sp=0xc000016fd8 pc=0x55aecb3d0a81
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110

goroutine 42 [syscall]:
runtime.notetsleepg(0x55aecde44400, 0xc34700, 0x1415)
	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000012f60 sp=0xc000012f30 pc=0x55aecb37eb08
runtime.timerproc(0x55aecde443e0)
	/usr/lib/golang/src/runtime/time.go:311 +0x2f5 fp=0xc000012fd8 sp=0xc000012f60 pc=0x55aecb3c1615
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000012fe0 sp=0xc000012fd8 pc=0x55aecb3d0a81
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110
toolbox: unable to migrate containers: Podman version couldn't be read
```

**Comment by giuseppe** [comment]
should be fixed in Podman now with https://github.com/containers/libpod/commit/ec940b08c6149d91cf969cb9b56299058c739735

**Comment by returntrip** [comment]
@giuseppe Thanks, was nearly logging a libpod issue

**Comment by debarshiray** [comment]
Thanks, @giuseppe 

Let's leave the `unable to migrate containers: Podman version couldn't be read` issue to https://github.com/containers/crun/issues/118, and use this one for the crash.

**Comment by returntrip** [comment]
I have tested with `podman-1.6.1-0.2.rc1.fc31.x86_64` and `toolbox: unable to migrate containers: Podman version couldn't be read` is gone.

One odd thing tho, as a one off I got this on exiting toolbox:

```
⬢[returntrip@toolbox returntrip]$ exit
logout
Error: non zero exit code: 1: OCI runtime error
```

**Comment by debarshiray** [comment]
> One odd thing tho, as a one off I got this on exiting toolbox:
> 
> ```
> ⬢[returntrip@toolbox returntrip]$ exit
> logout
> Error: non zero exit code: 1: OCI runtime error
> ```

Yes, I saw it once as well.
